### ISSUE TITLE
JCEF not enabled in 2022.1.3

### ISSUE THREAD

**Issue by penguinpee** [lkiesow/intellij-idea-community-rpm#3]
I installed [Markdown Editor plugin](https://plugins.jetbrains.com/plugin/17254-markdown-editor) in IntelliJ IDEA. The plugin requires JCEF, which should be enabled by default since [2020.2](https://plugins.jetbrains.com/docs/intellij/jcef.html#enabling-jcef). Yet Markdown Editor complains that it is not supported.

![no_support_for_JCEF](https://user-images.githubusercontent.com/98259694/179739944-0bb4eda9-b3e8-4bb7-918e-f1be73290921.png)

It could be a bug in Markdown Editor. How do I verify that JCEF is enabled in IntelliJ IDEA?

**Comment by lkiesow** [comment]
I don't think I can help you with this. I just repackage the binary tarballs. The process only removes a few files for other architectures or systems. I don't think this should effect this issue. Take a look at the [`intellij-idea-community.spec`](https://github.com/lkiesow/intellij-idea-community-rpm/blob/master/intellij-idea-community.spec) for more details.

But then looking at that plugin, the most recent comment on this (from May 2022) is that the plugin does not work due to some JCEF related error. So, maybe it's a general problem with that plugin.

**Comment by penguinpee** [comment]
> But then looking at that plugin, the most recent comment on this (from May 2022) is that the plugin does not work due to some JCEF related error. So, maybe it's a general problem with that plugin.

Thanks for your reply. I had a look at the plugin's GitHub issue list before I posted here. I didn't find anything that helped me further. Just wanted to make sure the prerequisites are met. I guess you are right and the issue is with the plugin.
