### ISSUE TITLE
Error in COPR builds

### ISSUE THREAD

**Issue by devinrsmith** [lkiesow/intellij-idea-community-rpm#6]
I've noticed there haven't been any new builds recently. I looked at the copr logs and noticed that the downloads aren't working: 

```
curl: (22) The requested URL returned error: 404
error: Couldn't download https://download.jetbrains.com/idea/ideaIC-2023.1.1-no-jbr.tar.gz
```

It looks like Jetbrains may no longer be providing the `no-jbr` version.

I've raised https://youtrack.jetbrains.com/issue/IDEA-319729/IntelliJ-Linux-without-JBR-downloads-no-longer-available, hoping to get an official response back.

**Comment by podhorsky-ksj** [comment]
I have question. Why wait for change in idea, which can never came, and keep unfunctional build?
There can be used the same patch as it is in archlinux - see https://gitlab.archlinux.org/archlinux/packaging/packages/intellij-idea-community-edition.
Just apply the patch during the package build and it should work. It is simple change.

**Comment by devinrsmith** [comment]
Thanks for the link. This repo actually uses the Jetbrains pre-built releases, but I like the approach Arch is taking as well. I'm not the maintainer of this library. I'd be happy to take on some of the responsibilities though, cc @lkiesow

**Comment by podhorsky-ksj** [comment]
I have  thought about creating copr account and do it by myself, but I will try this way first  because i don't like duplicities.
Better even build with jbr than failed builds. Now I'm using flatpak idea with java from host fedora, but I had to rewrite one symlink which java uses and which cannot be accessed by flatpak idea, so, rpm build idea would be better.

I'm not sure why idea isn't in normal fedora repo. Idea comunity has apache license, so there shouldn't be any issues.

**Comment by lkiesow** [comment]
I finally found the time to fix this. Most of the work was already done in #5. Just a few minor adjustments were needed. The repo should now be updated on a regular basis again.

> I'm not sure why idea isn't in normal fedora repo. 

The Fedora project has stricter rules of what can go in there (for good reasons!). You couldn't just download any binary from some project website and throw it in an RPM like I do here. And actually maintaining it properly would likely be a lot of work. That's why I never started packaging this officially at least.
