### ISSUE TITLE
Access to historical builds

### ISSUE THREAD

**Issue by devinrsmith** [lkiesow/intellij-idea-community-rpm#8]
I didn't realize that COPR doesn't keep "old" RPM builds. Updating to the latest 2024.1 release seems to be buggy for me (didn't have issues w/ 2023.3.6). I know this is not something you can solve, but any chance there is another way to get a Fedora 39 2023.3.6 RPM build?

**Comment by lkiesow** [comment]
Yes, Copr only keeps the latest version.
We would need to have another storage to keep older versions or add another separate package  (something like `intellij-idea-community-legacy`) which could be the previous release. If you want to add the automation for that to this repo, I'm happy to accept that.

Since the SPEC files are also still available, it shouldn't be too hard to build the RPMs again locally *if* the versions are still available from IntilliJ. Not sure what their policy is regarding older versions.
